version: '2'
services:
    php:
        build: .
        volumes:
            - ./www:/home/www
            - ./init:/home/init
        links:
            - rabbit
    rabbit:
        image: rabbitmq:3.7.5-management
        working_dir: /home
        
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password